document.write('<center>'); 
document.write('<img src="/starpy.png" width="100%" height="auto" alt="">'); 
document.write('<h1><u><i>The GrillOut</i></u></h1>'); 
document.write('<nav>'); 
document.write('<h2>');
document.write('<a href="https://literalgrill.com/home">Home</a> &#9733; '); 
document.write('<a href="/aboutme">About Me</a> &#9733; '); 
document.write('<a href="/archives.html">Archive</a> &#9733; '); 
document.write('<a href="/fansub_projects">Fansub Projects</a> &#9733; '); 
document.write('<a href="/games">Games</a> &#9733; '); 
document.write('<a href="/zines">Zines</a>'); 
document.write('</h2>'); 
document.write('</nav>'); 
document.write('<img src="/starpy.png" width="100%" height="auto" alt="">'); 
document.write('</center>'); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write('');
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write('');
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 
document.write(''); 

